name: Stackpack Build

on:
  push:
    branches: [ master, build-check ]
  pull_request:
    branches: [ master ]

jobs:
  build-stackpack:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile/Test/Package
      run: sbt compile test package

  test-agent-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Add pip repository
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: source .ci_scripts/setup_pip.sh
      - name: Install checksdev
        run: pip install stackstate_checks_dev[cli]
      - name: Run spunk base test
        run: ( cd agent-check && checksdev test splunk_base )


